- name: Mention External collaborators
  # You may pin to the exact commit or the version.
  # uses: pmanlukas/mention-external-collaborators@3c2c2663d9b64f56813b185ae46376b641d8caa2
  uses: saibiju/mention-external-collaborators@v2
  with:
    # token to authenticate with GitHub
    GitHub_Token: # optional, default is ${{ github.token }}
    # Number of issue
    Issue_Number: 
